[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[runner]
# Ab deployment Python 3.11 par hoga, jo TensorFlow ke liye compatible hai.
python_version = "3.11""
